/* Auto-generated stub libGL: empty no-op gl/glX symbols so Xvfb can
 * relocate + run its 2D/fbdev path WITHOUT Alpine mesa + the 153MB libLLVM
 * that blows blink wasm load-time memory. */
void glAccum(void){}
void glActiveTextureARB(void){}
void glAlphaFunc(void){}
void glAreTexturesResident(void){}
void glBegin(void){}
void glBindTexture(void){}
void glBitmap(void){}
void glBlendColor(void){}
void glBlendEquation(void){}
void glBlendFunc(void){}
void glCallList(void){}
void glCallLists(void){}
void glClear(void){}
void glClearAccum(void){}
void glClearColor(void){}
void glClearDepth(void){}
void glClearIndex(void){}
void glClearStencil(void){}
void glClipPlane(void){}
void glColor3bv(void){}
void glColor3dv(void){}
void glColor3fv(void){}
void glColor3iv(void){}
void glColor3sv(void){}
void glColor3ubv(void){}
void glColor3uiv(void){}
void glColor3usv(void){}
void glColor4bv(void){}
void glColor4dv(void){}
void glColor4fv(void){}
void glColor4iv(void){}
void glColor4sv(void){}
void glColor4ubv(void){}
void glColor4uiv(void){}
void glColor4usv(void){}
void glColorMask(void){}
void glColorMaterial(void){}
void glColorPointer(void){}
void glColorSubTable(void){}
void glColorTable(void){}
void glColorTableParameterfv(void){}
void glColorTableParameteriv(void){}
void glConvolutionFilter1D(void){}
void glConvolutionFilter2D(void){}
void glConvolutionParameterf(void){}
void glConvolutionParameterfv(void){}
void glConvolutionParameteri(void){}
void glConvolutionParameteriv(void){}
void glCopyColorSubTable(void){}
void glCopyColorTable(void){}
void glCopyConvolutionFilter1D(void){}
void glCopyConvolutionFilter2D(void){}
void glCopyPixels(void){}
void glCopyTexImage1D(void){}
void glCopyTexImage2D(void){}
void glCopyTexSubImage1D(void){}
void glCopyTexSubImage2D(void){}
void glCopyTexSubImage3D(void){}
void glCullFace(void){}
void glDeleteLists(void){}
void glDeleteTextures(void){}
void glDepthFunc(void){}
void glDepthMask(void){}
void glDepthRange(void){}
void glDisable(void){}
void glDisableClientState(void){}
void glDrawArrays(void){}
void glDrawBuffer(void){}
void glDrawPixels(void){}
void glEdgeFlagPointer(void){}
void glEdgeFlagv(void){}
void glEnable(void){}
void glEnableClientState(void){}
void glEnd(void){}
void glEndList(void){}
void glEvalCoord1dv(void){}
void glEvalCoord1fv(void){}
void glEvalCoord2dv(void){}
void glEvalCoord2fv(void){}
void glEvalMesh1(void){}
void glEvalMesh2(void){}
void glEvalPoint1(void){}
void glEvalPoint2(void){}
void glFeedbackBuffer(void){}
void glFinish(void){}
void glFlush(void){}
void glFogf(void){}
void glFogfv(void){}
void glFogi(void){}
void glFogiv(void){}
void glFrontFace(void){}
void glFrustum(void){}
void glGenLists(void){}
void glGenTextures(void){}
void glGetBooleanv(void){}
void glGetClipPlane(void){}
void glGetColorTable(void){}
void glGetColorTableParameterfv(void){}
void glGetColorTableParameteriv(void){}
void glGetConvolutionFilter(void){}
void glGetConvolutionParameterfv(void){}
void glGetConvolutionParameteriv(void){}
void glGetDoublev(void){}
void glGetError(void){}
void glGetFloatv(void){}
void glGetHistogram(void){}
void glGetHistogramParameterfv(void){}
void glGetHistogramParameteriv(void){}
void glGetIntegerv(void){}
void glGetLightfv(void){}
void glGetLightiv(void){}
void glGetMapdv(void){}
void glGetMapfv(void){}
void glGetMapiv(void){}
void glGetMaterialfv(void){}
void glGetMaterialiv(void){}
void glGetMinmax(void){}
void glGetMinmaxParameterfv(void){}
void glGetMinmaxParameteriv(void){}
void glGetPixelMapfv(void){}
void glGetPixelMapuiv(void){}
void glGetPixelMapusv(void){}
void glGetPolygonStipple(void){}
void glGetSeparableFilter(void){}
void glGetString(void){}
void glGetTexEnvfv(void){}
void glGetTexEnviv(void){}
void glGetTexGendv(void){}
void glGetTexGenfv(void){}
void glGetTexGeniv(void){}
void glGetTexImage(void){}
void glGetTexLevelParameterfv(void){}
void glGetTexLevelParameteriv(void){}
void glGetTexParameterfv(void){}
void glGetTexParameteriv(void){}
void glHint(void){}
void glHistogram(void){}
void glIndexMask(void){}
void glIndexPointer(void){}
void glIndexdv(void){}
void glIndexfv(void){}
void glIndexiv(void){}
void glIndexsv(void){}
void glIndexubv(void){}
void glInitNames(void){}
void glIsEnabled(void){}
void glIsList(void){}
void glIsTexture(void){}
void glLightModelf(void){}
void glLightModelfv(void){}
void glLightModeli(void){}
void glLightModeliv(void){}
void glLightf(void){}
void glLightfv(void){}
void glLighti(void){}
void glLightiv(void){}
void glLineStipple(void){}
void glLineWidth(void){}
void glListBase(void){}
void glLoadIdentity(void){}
void glLoadMatrixd(void){}
void glLoadMatrixf(void){}
void glLoadName(void){}
void glLogicOp(void){}
void glMap1d(void){}
void glMap1f(void){}
void glMap2d(void){}
void glMap2f(void){}
void glMapGrid1d(void){}
void glMapGrid1f(void){}
void glMapGrid2d(void){}
void glMapGrid2f(void){}
void glMaterialf(void){}
void glMaterialfv(void){}
void glMateriali(void){}
void glMaterialiv(void){}
void glMatrixMode(void){}
void glMinmax(void){}
void glMultMatrixd(void){}
void glMultMatrixf(void){}
void glMultiTexCoord1dvARB(void){}
void glMultiTexCoord1fvARB(void){}
void glMultiTexCoord1ivARB(void){}
void glMultiTexCoord1svARB(void){}
void glMultiTexCoord2dvARB(void){}
void glMultiTexCoord2fvARB(void){}
void glMultiTexCoord2ivARB(void){}
void glMultiTexCoord2svARB(void){}
void glMultiTexCoord3dvARB(void){}
void glMultiTexCoord3fvARB(void){}
void glMultiTexCoord3ivARB(void){}
void glMultiTexCoord3svARB(void){}
void glMultiTexCoord4dvARB(void){}
void glMultiTexCoord4fvARB(void){}
void glMultiTexCoord4ivARB(void){}
void glMultiTexCoord4svARB(void){}
void glNewList(void){}
void glNormal3bv(void){}
void glNormal3dv(void){}
void glNormal3fv(void){}
void glNormal3iv(void){}
void glNormal3sv(void){}
void glNormalPointer(void){}
void glOrtho(void){}
void glPassThrough(void){}
void glPixelMapfv(void){}
void glPixelMapuiv(void){}
void glPixelMapusv(void){}
void glPixelStoref(void){}
void glPixelStorei(void){}
void glPixelTransferf(void){}
void glPixelTransferi(void){}
void glPixelZoom(void){}
void glPointSize(void){}
void glPolygonMode(void){}
void glPolygonOffset(void){}
void glPolygonStipple(void){}
void glPopAttrib(void){}
void glPopMatrix(void){}
void glPopName(void){}
void glPrioritizeTextures(void){}
void glPushAttrib(void){}
void glPushMatrix(void){}
void glPushName(void){}
void glRasterPos2dv(void){}
void glRasterPos2fv(void){}
void glRasterPos2iv(void){}
void glRasterPos2sv(void){}
void glRasterPos3dv(void){}
void glRasterPos3fv(void){}
void glRasterPos3iv(void){}
void glRasterPos3sv(void){}
void glRasterPos4dv(void){}
void glRasterPos4fv(void){}
void glRasterPos4iv(void){}
void glRasterPos4sv(void){}
void glReadBuffer(void){}
void glReadPixels(void){}
void glRectdv(void){}
void glRectfv(void){}
void glRectiv(void){}
void glRectsv(void){}
void glRenderMode(void){}
void glResetHistogram(void){}
void glResetMinmax(void){}
void glRotated(void){}
void glRotatef(void){}
void glScaled(void){}
void glScalef(void){}
void glScissor(void){}
void glSelectBuffer(void){}
void glSeparableFilter2D(void){}
void glShadeModel(void){}
void glStencilFunc(void){}
void glStencilMask(void){}
void glStencilOp(void){}
void glTexCoord1dv(void){}
void glTexCoord1fv(void){}
void glTexCoord1iv(void){}
void glTexCoord1sv(void){}
void glTexCoord2dv(void){}
void glTexCoord2fv(void){}
void glTexCoord2iv(void){}
void glTexCoord2sv(void){}
void glTexCoord3dv(void){}
void glTexCoord3fv(void){}
void glTexCoord3iv(void){}
void glTexCoord3sv(void){}
void glTexCoord4dv(void){}
void glTexCoord4fv(void){}
void glTexCoord4iv(void){}
void glTexCoord4sv(void){}
void glTexCoordPointer(void){}
void glTexEnvf(void){}
void glTexEnvfv(void){}
void glTexEnvi(void){}
void glTexEnviv(void){}
void glTexGend(void){}
void glTexGendv(void){}
void glTexGenf(void){}
void glTexGenfv(void){}
void glTexGeni(void){}
void glTexGeniv(void){}
void glTexImage1D(void){}
void glTexImage2D(void){}
void glTexImage3D(void){}
void glTexParameterf(void){}
void glTexParameterfv(void){}
void glTexParameteri(void){}
void glTexParameteriv(void){}
void glTexSubImage1D(void){}
void glTexSubImage2D(void){}
void glTexSubImage3D(void){}
void glTranslated(void){}
void glTranslatef(void){}
void glVertex2dv(void){}
void glVertex2fv(void){}
void glVertex2iv(void){}
void glVertex2sv(void){}
void glVertex3dv(void){}
void glVertex3fv(void){}
void glVertex3iv(void){}
void glVertex3sv(void){}
void glVertex4dv(void){}
void glVertex4fv(void){}
void glVertex4iv(void){}
void glVertex4sv(void){}
void glVertexPointer(void){}
void glViewport(void){}
void glXGetProcAddressARB(void){}
